name: Elixir CI Workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  elixir_ci:
    name: Elixir CI
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Erlang/OTP + Elixir
      id: setup-beam
      uses: erlef/setup-beam@v1
      with:
        otp-version: '24.0' # Version range or exact (required)
        elixir-version: '1.12.0' # Version range or exact (required)
        # install-hex: true (default)
        # install-rebar: true (default)

    - name: Restore dependency/build cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        # cache key is hierarchical:
        #   OS, otp-version, elixir-version, mix.lock
        key: ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-
          ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-
          ${{ runner.os }}-mix-
        
    - name: Dependencies
      run: |
        mix deps.get
        mix deps.compile

    - name: Code
      run: |
        mix format --check-formatted
        mix compile --warnings-as-errors
        mix credo --strict
        mix dialyzer
        mix docs
 
    - name: Test
      run: |
        mix test --warnings-as-errors --cover --export-coverage default
        mix test.coverage
